name: ${project.artifactId}
main: io.github.lxgaming.antiexploit.AntiExploit
version: ${project.version}
author: LX_Gaming
website: http://www.lxgaming.github.io
commands:
  antiexploit:
    description: Display plugin information.
    usage: /<command>
permissions:
  AntiExploit.Bypass:
    description: Bypass AntiExploit System.
  AntiExploit.AlertStaff:
    description: Players with this permission will get alerted with StaffMessage.
  AntiExploit.Admin:
    description: Provides extra information when running '/antiexploit'.