AntiExploit:
  # For development purposes.
  Debug: false
  Exploits:
    # Players with modified clients are able to fly.
    Fly:
      # Prevent this type of Exploit?
      Prevent: true
      # Damage the player if caught? ('0D' will disable damage)
      Damage: 0D
      # Ban the player if caught?
      Ban: false
      # Kick the player if caught?
      Kick: true
      # Broadcast to the entire server that this player attempted an Exploit?
      Broadcast: false
      # Alert staff on the server that this player attempted an Exploit?
      AlertStaff: true
      # Message to broadcast.
      BroadcastMessage: "&cNobody likes hackers,&f %playername%"
      # Message to send to staff.
      StaffMessage: "&8[&cAlert&8]&f %playername% &8attempted to use %exploit% Exploit!"
      # Message to provided when kicking the player.
      KickMessage: "&8[&cAntiExploit&8] detected %exploit% Exploit!"
      # Message to provided when banning the player.
      BanMessage: "&8[&cAntiExploit&8] detected %exploit% Exploit!"
    # Players can see though the world if their head is inside a leaf block.
    LeavesXRay:
      # Prevent this type of Exploit?
      Prevent: true
      # Damage the player if caught?
      Damage: 2D
      # Ban the player if caught?
      Ban: false
      # Kick the player if caught?
      Kick: true
      # Broadcast to the entire server that this player attempted an Exploit?
      Broadcast: false
      # Alert staff on the server that this player attempted an Exploit?
      AlertStaff: true
      # Message to broadcast.
      BroadcastMessage: "&cNobody likes hackers,&f %playername%"
      # Message to send to staff.
      StaffMessage: "&8[&cAlert&8]&f %playername% &8attempted to use %exploit% Exploit!"
      # Message to provided when kicking the player.
      KickMessage: "&8[&cAntiExploit&8]\n&fDetected %exploit% Exploit!"
      # Message to provided when banning the player.
      BanMessage: "&8[&cAntiExploit&8]\n&fDetected %exploit% Exploit!"
    # Players with modified client can run/fly fast than normal.
    Speed:
      # Prevent this type of Exploit?
      Prevent: true
      # Damage the player if caught? ('0D' will disable damage)
      Damage: 0D
      # Ban the player if caught?
      Ban: false
      # Kick the player if caught?
      Kick: true
      # Broadcast to the entire server that this player attempted an Exploit?
      Broadcast: false
      # Alert staff on the server that this player attempted an Exploit?
      AlertStaff: true
      # Message to broadcast.
      BroadcastMessage: "&cNobody likes hackers,&f %playername%"
      # Message to send to staff.
      StaffMessage: "&8[&cAlert&8]&f %playername% &8attempted to use %exploit% Exploit!"
      # Message to provided when kicking the player.
      KickMessage: "&8[&cAntiExploit&8] detected %exploit% Exploit!"
      # Message to provided when banning the player.
      BanMessage: "&8[&cAntiExploit&8] detected %exploit% Exploit!"